apiVersion: batch/v1
kind: Job
metadata:
    name: train-job
spec:
    template:
        spec:
            containers:
                - name: train
                  image: wduan10/ml_model
            restartPolicy: Never
    backoffLimit: 4
